/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors/index";
import * as FileForge from "../index";

export class BadGatewayError extends errors.FileForgeError {
    constructor(body: FileForge.ErrorSchema) {
        super({
            message: "BadGatewayError",
            statusCode: 502,
            body: body,
        });
        Object.setPrototypeOf(this, BadGatewayError.prototype);
    }
}
