/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class FileForgeTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, FileForgeTimeoutError.prototype);
    }
}
