/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as FileForge from "../../../../api/index";
import * as core from "../../../../core";

export const PostPdfMergeRequestOptions: core.serialization.ObjectSchema<
    serializers.PostPdfMergeRequestOptions.Raw,
    FileForge.PostPdfMergeRequestOptions
> = core.serialization.object({});

export declare namespace PostPdfMergeRequestOptions {
    interface Raw {}
}
