/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Fileforge from "../../index";

/**
 * @example
 *     {}
 */
export interface GenerateRequest {
    /** Conversion options. This field is required even if empty. */
    options: Fileforge.GenerateRequestOptions;
}
