/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FileForge from "../../index";

/**
 * @example
 *     {}
 */
export interface MergeRequest {
    options: FileForge.MergeRequestOptions;
}
