/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Fileforge from "../../index";

/**
 * @example
 *     {}
 */
export interface MergeRequest {
    options: Fileforge.MergeRequestOptions;
}
