/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Fileforge from "../../api/index";
import * as core from "../../core";

export const ConvertDocxRequestOptions: core.serialization.ObjectSchema<
    serializers.ConvertDocxRequestOptions.Raw,
    Fileforge.ConvertDocxRequestOptions
> = core.serialization.object({
    templateLiterals: core.serialization.record(core.serialization.string(), core.serialization.string()).optional(),
});

export declare namespace ConvertDocxRequestOptions {
    interface Raw {
        templateLiterals?: Record<string, string> | null;
    }
}
