/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as FileForge from "../../api/index";
import * as core from "../../core";

export const GenerateRequestOptions: core.serialization.ObjectSchema<
    serializers.GenerateRequestOptions.Raw,
    FileForge.GenerateRequestOptions
> = core.serialization.object({
    world: core.serialization.string().optional(),
});

export declare namespace GenerateRequestOptions {
    interface Raw {
        world?: string | null;
    }
}
