/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Fileforge from "../../api/index";
import * as core from "../../core";

export const MergeRequestOptions: core.serialization.ObjectSchema<
    serializers.MergeRequestOptions.Raw,
    Fileforge.MergeRequestOptions
> = core.serialization.object({});

export declare namespace MergeRequestOptions {
    interface Raw {}
}
