/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const FileForgeEnvironment = {
    Default: "https://30c1-2a01-cb00-286-f500-f58d-848f-e524-f098.ngrok-free.app",
} as const;

export type FileForgeEnvironment = typeof FileForgeEnvironment.Default;
