/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const FileForgeEnvironment = {
    Default: "https://api.fileforge.com",
} as const;

export type FileForgeEnvironment = typeof FileForgeEnvironment.Default;
